ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls',namespace="store"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name="store"
urlpatterns = [
path('',views.store,name="store"),
path('cart/',views.cart,name="cart"),
path('checkout/',views.checkout,name="checkout"),
path('update_item/',views.updateItem,name="update-item"),
path('process_order/',views.processOrder,name="process-order")

]

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=200,null=True)
    email = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200,null=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    digital = models.BooleanField(default=False,null=True,blank=False)
    image= models.ImageField(null=True,blank=True) 
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url=""
        return url

class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True,blank=False)
    transaction_id = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    @property
    def shipping(self):
        shipping=False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital==False:
                 shipping=True
        return shipping
class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null= True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_orderd = models.DateTimeField(auto_now_add=True)
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=200,null=True)
    zipcode = models.CharField(max_length=200,null=True)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.address

store/views.py
import json
import datetime
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import *
from .utils import cartData,guestUser
# Create your views here.

def store(request):
    data = cartData(request)
    cartItems =data['cartItems']

    products = Product.objects.all()
    context = {"products":products,"cartItems":cartItems}
    return render(request,'store/store.html',context)


def cart(request):
    data = cartData(request)
    cartItems =data['cartItems']
    order = data['order']
    items= data['items']

    context = {"items":items,"order":order,"cartItems":cartItems}
    return render(request,'store/cart.html',context)
    
def checkout(request):
    data = cartData(request)
    cartItems =data['cartItems']
    order = data['order']
    items= data['items']

    context = {"items":items,"order":order,"cartItems":cartItems}
    return render(request,'store/checkout.html',context)

@csrf_exempt
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    customer =request.user.customer
    product = Product.objects.get(id=productId)
    
    order,created = Order.objects.get_or_create(customer=customer,complete=False)
    orderItem,created=OrderItem.objects.get_or_create(order=order,product=product)
    if action=='add':
        orderItem.quantity=(orderItem.quantity+1)
    elif action=='remove':
        orderItem.quantity=(orderItem.quantity-1)
    orderItem.save()

    if orderItem.quantity <=0:
        orderItem.delete()
    return JsonResponse('Item was added',safe=False)
   
@csrf_exempt
def processOrder(request):
    print(request.body)
    transaction_id=datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order,created = Order.objects.get_or_create(customer=customer,complete=False)
        if order.shipping==True:
            ShippingAddress.objects.create(customer=customer,order=order,address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'])
    
    else:
        order,customer  =guestUser(request,data)
    total = float(data['form']['total'])
    order.transaction_id=transaction_id
    if total == order.get_cart_total:
        order.complete=True
    order.save()

    if order.shipping==True:
        ShippingAddress.objects.create(customer=customer,order=order,address=data['shipping']['address'],
        city=data['shipping']['city'],
        state=data['shipping']['state'],
        zipcode=data['shipping']['zipcode'])

    return JsonResponse("Payment Complete",safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %} {% load static %} {% block title %}Cart 
{% endblock title %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="box-element">
      <a class="btn btn-outline-dark" href="{% url 'store:store' %}"
        >&#x2190; Contine Shopping</a
      >
      <br />
      <br />
      <table class="table">
        <tr>
          <th>
            <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
          </th>
          <th>
            <h5>
              Total: <strong>Rs {{order.get_cart_total|floatformat:2}} </strong>
            </h5>
          </th>
          <th>
            <a
              style="float: right; margin: 5px;"
              href="{% url 'store:checkout' %}"
              class="btn btn-success"
              >Checkout</a
            >
          </th>
        </tr>
      </table>
    </div>
    <br />
    <div class="box-element">
      <div class="cart-row">
        <div style="flex: 2;"></div>
        <div style="flex: 2;"><strong>Item</strong></div>
        <div style="flex: 1;"><strong>Price</strong></div>
        <div style="flex: 1;"><strong>Qty</strong></div>
        <div style="flex: 1;"><strong>Total</strong></div>
      </div>
      {% for item in items %}
      <div class="cart-row">
        <div style="flex: 2;">
          <img class="row-image" src="{{item.product.imageURL}}" alt="" />
        </div>
        <div style="flex: 2;">{{itme.product.name}}</div>
        <div style="flex: 1;">Rs {{item.product.price|floatformat:2}}</div>
        <div style="flex: 1;">
          <p class="quantity">{{item.quantity}}</p>
          <div class="quantity">
            <img
              data-product="{{item.product.id}}"
              data-action="add"
              src="{% static 'images/arrow-up.png' %}"
              alt="Up Arrow"
              class="chg-quantity update-cart"
            />
            <img
              data-product="{{item.product.id}}"
              data-action="remove"
              src="{% static 'images/arrow-down.png' %}"
              alt="Down Arrow"
              class="chg-quantity update-cart"
            />
          </div>
        </div>
        <div style="flex: 1;">Rs {{item.get_total|floatformat:2}}</div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

store/templates/store/checkout.html
{% extends 'store/main.html' %} {% load static %} {% block title %} Checkout 
{% endblock title %} {% block content %}
<div class="row">
  <div class="col-lg-6">
    <div class="box-element" id="form-wrapper">
      <form action="" id="form">
        <!-- {% csrf_token %} -->
        <div id="user-info">
          <div class="form-field">
            <input
              required
              class="form-control"
              type="text"
              name="name"
              placeholder="Name.."
            />
          </div>
          <div class="form-field">
            <input
              required
              class="form-control"
              type="email"
              name="email"
              placeholder="Email.."
            />
          </div>
        </div>
        <div id="shipping-info">
          <hr />
          <p>Shipping Information:</p>
          <hr />
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="address"
              placeholder="Address.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="city"
              placeholder="City.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="state"
              placeholder="State.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="zipcode"
              placeholder="Zip code.."
            />
          </div>
          <div class="form-field">
            <input
              class="form-control"
              type="text"
              name="country"
              placeholder="Country..."
            />
          </div>
        </div>
        <hr />
        <input
          id="form-button"
          class="btn btn-success btn-block"
          type="submit"
          value="Continue "
        />
      </form>
    </div>
    <br />
    <div class="box-element hidden" id="payment-info">
      <small>Paypal Options</small>
      <button class="btn btn-success" id="make-payment">Make Payment</button>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="box-element">
      <a href="{% url 'store:cart' %}" class="btn btn-outline-dark"
        >&#x2190; Back to Cart</a
      >
      <hr />
      <h3>Order Summary</h3>
      <hr />
      {% for item in items %}
      <div class="cart-row">
        <div style="flex: 2;">
          <img class="row-image" src="{{item.product.imageURL}}" %}" />
        </div>
        <div style="flex: 2;"><p>{{item.product.name}}</p></div>
        <div style="flex: 2;"><p>Rs {{item.product.price}}</p></div>
        <div style="flex: 1;"><p>x{{item.quantity}}</p></div>
      </div>
      {% endfor %}
      <h5>Items: {{order.get_cart_items}}</h5>
      <h5>Total: Rs {{order.get_cart_total|floatformat:2}}</h5>
    </div>
  </div>
</div>

<script type="text/javascript">
    var shipping = "{{order.shipping}}";
    var total = "{{order.get_cart_total}}";
    if (shipping === "False") {
      document.getElementById("shipping-info").innerHTML = "";
    }
    if (user !== "AnonymousUser") {
      document.getElementById("user-info").innerHTML = "";
    }

    if (shipping === "False" && user !== "AnonymousUser") {
      document.getElementById("form-wrapper").classList.add("hidden");
      document.getElementById("payment-info").classList.remove("hidden");
    }

    var form = document.getElementById("form");
  // csrftoken=form.getElementsByTagName('input')[0].value
  // console.log("csrftoken",csrftoken)
  form.addEventListener("submit", function (e) {
      e.preventDefault();
      console.log("form submited");
      document.getElementById("form-button").classList.add("hidden");
      document.getElementById("payment-info").classList.remove("hidden");
    });
    document
      .getElementById("make-payment")
      .addEventListener("click", function (e) {
        submitFormData();
      });
    function submitFormData() {
      var userFormData = {
        name: null,
        email: null,
        total: total,
      };
      var shippingInfo = {
        address: null,
        city: null,
        state: null,
        zipcode: null,
      };
      console.log("Form", form.address);
      if (shipping !== "False") {
        shippingInfo.address = form.address.value;
        shippingInfo.city = form.city.value;
        shippingInfo.state = form.state.value;
        shippingInfo.zipcode = form.zipcode.value;
      }
      if (user == "AnonymousUser") {
        userFormData.name = form.name.value;
        userFormData.email = form.email.value;
      }
      var url = "/process_order/";
      fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
      },
        body: JSON.stringify({
          form: userFormData,
          shipping: shippingInfo,
        }),
      })
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          console.log("Success", data);
          alert("Transaction Completed");
          cart = {};
          document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/";
          window.location.href = "{% url 'store:store' %}";
        });
    }
</script>
{% endblock content %}

store/templates/store/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"
    />
    <script type="text/javascript">
      var user = "{{request.user}}";
      // async function getToken(name) {
      //   var cookieValue = null;
      //   if (document.cookie && document.cookie !== "") {
      //     var cookies = document.cookie.split(";");
      //     for (var i = 0; i < cookies.length; i++) {
      //       var cookie = cookies[i].trim();

      //       // Does this cookie string begin with the name we want?

      //       if (cookie.substring(0, name.length + 1) === name + "=") {
      //         cookieValue = decodeURIComponent(
      //           cookie.substring(name.length + 1)
      //         );
      //       }
      //     }
      //   }
      //   return cookieValue;
      // }
      // var csrftoken = getToken("csrftoken");
      // console.log("csrftoken", csrftoken);
      function getCookie(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");
        // Loop through the array elements
        for (var i = 0; i < cookieArr.length; i++) {
          var cookiePair = cookieArr[i].split("=");

          /* Removing whitespace at the beginning of the cookie name
                     and compare it with the given string */
          if (name == cookiePair[0].trim()) {
            // Decode the cookie value and return
            return decodeURIComponent(cookiePair[1]);
          }
        }

        // Return null if not found
        return null;
      }
      var cart = JSON.parse(getCookie("cart"));

      if (cart == undefined) {
        cart = {};
        console.log("Cart Created!", cart);
        document.cookie = "cart=" + JSON.stringify(cart) + ";domain=;path=/";
      }
    </script>

    <title>Ecom-{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <!-- Overriding call bg-dark to bg-dark-theme -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark-theme">
      <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:store' %}"
              >Store <span class="sr-only">(current)</span></a
            >
          </li>
        </ul>

        <div class="form-inline my-2 my-lg-0">
          <a href="#" class="btn btn-warning">Login</a>

          <a href="{% url 'store:cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}" />
          </a>

          {% if cartItems > 0 %}
          <p id="cart-total">{{cartItems}}</p>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %} {% endblock content %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
  </body>
</html>

store/templates/store/store.html
{% extends 'store/main.html' %} {% load static %} {% block title %} Store 
{% endblock title %} {% block content %}
<div class="row">
  {% for product in products %}
  <div class="col-lg-4">
    <img class="thumbnail" src="{{product.imageURL}}" />
    <div class="box-element product">
      <h6><strong>{{product.name}}</strong></h6>
      <hr />
      <button
        data-product="{{product.id}}"
        data-action="add"
        class="btn btn-outline-secondary add-btn update-cart"
      >
        Add to Cart
      </button>
      <a href="#" class="btn btn-outline-success">View</a>
      <h4 style="display: inline-block; float: right;">
        Rs {{product.price|floatformat:2}}
      </h4>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}